
spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket:
        name: dhk-bucket
        url: https://dhk-bucket.s3.ap-northeast-2.amazonaws.com/
    region:
      static: ap-northeast-2
    stack:
      auto: false


